# Generated by Django 4.1.3 on 2022-11-27 18:14

import django.core.validators
from django.db import migrations, models


def create_instance(apps, schema_editor):
    Settings = apps.get_model('balancer', 'WorkersSettings')
    Settings.objects.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paralel_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], default=1)),
                ('clients_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], default=1)),
                ('max_servers_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], default=1)),
            ],
        ),
        migrations.RunPython(create_instance, migrations.RunPython.noop)
    ]
