# Generated by Django 4.1.3 on 2022-11-27 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0001_create_workers_settings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerssettings',
            name='prefered_load',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
