# Generated by Django 4.1.3 on 2022-11-27 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0002_added_prefered_load_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerssettings',
            options={'verbose_name': 'WorkersSettings', 'verbose_name_plural': 'WorkersSettings'},
        ),
        migrations.AddField(
            model_name='workerssettings',
            name='worker_timeout',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
