# Generated by Django 4.1.3 on 2022-11-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0003_add_worker_timeout_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerssettings',
            old_name='paralel_count',
            new_name='min_servers_count',
        ),
    ]
