# Generated by Django 4.1.3 on 2022-11-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_change_type_of_points_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='points',
        ),
    ]
