# Generated by Django 4.1.3 on 2022-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_removed_unused_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='method',
            field=models.CharField(choices=[('Nearest', 'Nearest')], max_length=50),
        ),
    ]
