# Generated by Django 4.1.3 on 2022-11-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_change_method_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='method',
        ),
    ]
